### PR TITLE
Added menus and ability to load and save the edit window to a file

### PR DESCRIPTION
**Pull request by sabarnett**
One of the issues I have is the need to copy and paste JSON in to the text box. If I already have a file I have to open it in another editor and copy/paste it in. If I then make changes to the file to fine tune it, I have to copy and paste it back to the original file. So, I have added a File menu to allow me to load a JSON file and to Save or SaveAs that file back to disk. 

I also created a JSON menu with an option to validate (alt-V) the JSON without having to run through the generate process.

The Close and About buttons have been moved to the menus.

### CODE REVIEW

**Comment by suntong** [comment]
That's excellent! Thanks for your contribution!

Just trying to understand what you are doing -- you are basically opening up a .json file and save it back (functionally) as a .cs file (for the struct), right?

**Comment by sabarnett** [comment]
I kept things simple. There is now a file menu with Load, Save and Save As. Load prrompts you for a file with type .json and loads it in to the edit box. Save saves it back and save as saves it with a new file name. The generate process remains the same, so that's how you will save the cs file(s).

The Json I have wanted to convert has generally been in an existing .json file, so this is easier than typing it in.

**Comment by suntong** [comment]
That's great. 

I'll check it out on Monday, meanwhile, if you could write some blurb about it at https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/wiki/Major-enhancements-since-the-fork, from the end user usage prospective, that'll be great.

**Comment by sabarnett** [comment]
Sorry suntong, but I have no idea how to edit the wiki. It gives me no editing capabilities and this is the first time I've contributed to a project, so I'm kind of making this up as I go along! However, were I able to work out what to do, I would add:

--------

The purpose of this change was to provide the application with a windows standard menu that can be used to extend the functionality in the program without adding more buttons to the UI. To that end, three top level menus have been provided; File, Json and Help. These encompass the following functionality:

+ **File -> Load Json File** - Gives you the ability to browse to a JSON file on disk and load it in to the edit window ready for editing.
+ **File -> Save Json File** - Saves the current edit window back to disk if you have made changes to it. If you have not previously opened a file (i.e. you just started editing Json), you will be prompted for the name of the file to save. _Ctrl+S_
+ **File -> Save Json As** - Saves the current edit window to disk. You will be prompted for the name of the file you want to create/overwrite.
+ **File -> Close Json File** - Closes the last opened file and clears the edit window.
+ **File -> Exit** - Closes the program. _Alt+F4_
 
+ **Json -> Paste & Go** - Is the same paste/convert functionality provided by the corresponding button. _F9_
+ **Json -> Generate** - Is the same code generation functionality provided by the Generate button. _Alt_G_
+ **Json -> Validate** - Attempts to validate the JSON in the edit window. You will be presented with a diagnostic message if there is a problem with the file or a success message of the file is correctly formatted. _Alt+V_
 
+ **Help -> About** - Displays program version and copyright information. _F1_

**Comment by suntong** [comment]
Oh, thanks a lot. 

No worry, I'll put it in. Editing the wiki should be nothing different than what you've put it here. 

Strange that you have no editing capabilities. I need to fix this. I've took a look at the settings and everything looks normal. 

This is what I have when looking at other's wiki, 

2017-08-21 14_15_26-jump start the cli based project mkideal_cli wiki

So you are not seeing the "Edit" button?

**Comment by sabarnett** [comment]
This is what I am seeing:

image

**Comment by suntong** [comment]
How about now?

**Comment by suntong** [comment]
The wiki _should be_ open for editing to the public, without any tweaking. I've just edited your wiki -- https://github.com/sabarnett/JsonCSharpClassGenerator/wiki

Still don't know what's special about this wiki.

**Comment by sabarnett** [comment]
Yep, I have the edit button now. Thanks.

**Comment by suntong** [comment]
Good. Thanks. 

Somehow I must have touched and click-enabled this option, FTR:

2017-08-21 14_46_38-options

**Pull request merged**
